### ISSUE TITLE
No External GPU detected...

### ISSUE THREAD

**Issue by mattyd2** [goalque/automate-eGPU#16]
Hello,

I have a MacBook Pro and a Geforce Titan Black card in a Sonnet Express and when I run the script it states that no eGPU is detected.

"Thunderbolt device is connected, but no external GPUs detected."

Does the script support Titan Black cards?

OSx 10.10.5

**Comment by goalque** [comment]
Yes, it does. This is a common error when there is a hardware/power issue.

https://www.techinferno.com/index.php?/forums/topic/7989-script-automating-the-installation-of-egpu-on-os-x-inc-display-output/&do=findComment&comment=138653

**Comment by goalque** [comment]
https://www.techinferno.com/index.php?/forums/topic/7989-script-automating-the-installation-of-egpu-on-os-x-inc-display-output/&do=findComment&comment=139692

**Comment by mattyd2** [comment]
thank you!

**Comment by gavner25** [comment]
I have the same issue as you guys. I get the error 'Thunderbolt device is connected, but no external GPUs detected'. 
 
I have the aikitio pci box with gtx 980ti & 750w supernova psu. using sierra os on late 2013 IMAC 27 in.

All lights on Aikitio, & GTX are on, fans are all on. PSU with paperclip working with fan on. 

Any ideas?

**Comment by tksppank** [comment]
i have gotten the same issue on my MacBook Pro 15" 2014 and a GTX 970 on an Akitio Thunder2 using the dell da-2 to power the cassis and the card. the card seemed to turn on, but i got this, did i break something?
<img width="430" alt="screen shot 2017-02-19 at 6 24 39 pm" src="https://cloud.githubusercontent.com/assets/16637453/23108360/d75cdc16-f6d1-11e6-9bc6-fd08a873b995.png">

**Comment by gavner25** [comment]
The issue for me was that the power supply was not powered up correctly when using the paperclip trick. Even though the paperclip was connected and the psu turns on, the papclick was inserted on the wrong side of the plug. I put the paperclip on the other side of the plug in the opposite holes and the issue was solved. Does that make sense ??

**Comment by garceri** [comment]
Just to let you know and for the record, we ran into a similar issue and the culprit was the ribbon cable we were using to attach the GPU card to the Thunderbolt box ( card doesn't fit the box) had some unsoldered pins/cables

Since a picture is worth more than a thousand words here is what it looked like:

![image](https://cloud.githubusercontent.com/assets/10517648/26412089/fcbd2b82-407d-11e7-8312-e45836300dee.png)

**Comment by mobilewebproject** [comment]
I have the same message 
Macbook pro 2015 15'' and GTX 1080 ti.
the gpu are on , GTX are on, fans are all on.

best regards

**Comment by gunkmogo** [comment]
@mobilewebproject you need https://github.com/KhaosT/tb3-enabler most likely before you run automate-eGPU.sh. I had the same issue with the exact same macbook and eGPU and this TB3 enabler script let me move ahead with automate-eGPU.sh.

**Comment by gunkmogo** [comment]
@eyaconsulting Did you try to restart the laptop without the TB cable plugged in? I needed the restart without the TB cable and plug it in after the reboot to make it work. You should see the eGPU enclosure under System report -> Thunderbolt bus once you hot plugged it.
