### ISSUE TITLE
usb 3 eGPU support

### ISSUE THREAD

**Issue by sammcj** [goalque/automate-eGPU#2]
It would be great if this patch could also enable USB 3.x eGPU passthrough.

- Example of one example working: https://www.youtube.com/watch?v=oq2wQB8SuQs
- Example enclosure: http://www.alibaba.com/product-detail/PCIe-to-dual-PCI-card-adapter_956451228.html?spm=a2700.7724857.35.1.9SGwKc

**Comment by goalque** [comment]
"The problem is the transport protocol. eGPUs use PCIe and there is no readily available driver to deliver a PCIe over USB 3.0. The demo above worked only because they used a heavily modified S3 video driver. "
http://forum.techinferno.com/diy-e-gpu-projects/7417-thunderbolt-2-egpu-%5Bosx%5D-%5Bwinsows-8-1%5D-mxm-pcie-%24350-%24480-shipping-3.html#post104519

**Comment by sammcj** [comment]
Poop
