### ISSUE TITLE
[Issues] eGPU on MBP

### ISSUE THREAD

**Issue by AurumNemo** [goalque/automate-eGPU#43]
Hi! May I ask some questions?
1. Does the script (0.9.9) support R9 Nano or RX 400 Graphics Cards? You said it's in experiments and I haven't find the codenames of them in the script.
2. I'd like to use the internal display on MBP (macOS). Can I use internal display after booting into macOS and will the eGPU do the calculations? (Someone in the forum told that an ex display is still required)

Thanks for creating such good things!

**Comment by goalque** [comment]
My pleasure!

1) No. As you can see in release notes, I’ve stroke out “Native support (experimental) for R9 Nano and RX 480”, because Baffin personality is currently placed in AMDRadeonX4100.kext
2) CUDA/OpenCL/Metal calculation is possible without an external monitor if the application can utilize external GPUs. Since most apps are not designed with eGPUs in mind, you should contact the developers if such a feature will be available in the future.

automate-eGPU.sh v1.0.0 will be released in the near future.

**Comment by AurumNemo** [comment]
1. Polaris 11 can be seen in RadeonX4100 and 9500Controller right now and in the macOS 10.12.2 Beta more GPUs appear. I think that in the future Radeon 400 will all work on macOS (just guess).
2. What about games based on OpenGL? I'm not a pro programmer so I don't know. I'm sure that eGPU can work with internal display (this can be realized on Windows) as 750M and M370X also transmit back graphics to Intel GPUs (which the internal display connected to).

It's a good news to hear that! Thanks for answering!
